apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redbus-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: redbus.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redbus-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: redbus-backend
                port:
                  number: 5000
