apiVersion: apps/v1
kind: Deployment
metadata:
  name: redbus-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redbus-backend
  template:
    metadata:
      labels:
        app: redbus-backend
    spec:
      containers:
        - name: backend
          image: soham22202/redbus-backend:1.0
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/redbus
